server:
  port: 8089
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://10.10.1.242:3306/order?useUnicode=true&characterEncoding=utf8
        username: sofmit
        password: sofmit


logging:
    level:
        root: error
        com.cf: debug

    path: "./logs"

